// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usmhbawkkfzhcpaiepbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbWhiYXdra2Z6aGNwYWllcGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzEyODcsImV4cCI6MjA3MDEwNzI4N30.Gffux1JhdiNDZBDe6qTqiVpUDksFBewzlK7hqAK742E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});